coordination/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from coordination.models import Quest
from . import views

quest_patterns = [
    path('quests/', views.all_quests, name='quests'),
    path('quests/new/', include([
        path('l/', views.create_quest, {'type': Quest.LINEAR}, name='quest_new_l'),
        path('nl/', views.create_quest, {'type': Quest.NONLINEAR}, name='quest_new_nl'),
        # TODO MC: 02.01.2019 uncomment when re-implement LNL quest
        # path('lnl/', views.create_quest, {'type': Quest.LINE_NONLINEAR}, name='quest_new_lnl'),
        path('ml/', views.create_quest, {'type': Quest.MULTILINEAR}, name='quest_new_ml'),
        path('type/', views.type_quest, name='quest_new_type'),
    ])),
    path('quests/<int:quest_id>/', include([
        path('', views.detail_quest, name='quest_detail'),
        path('edit/', views.edit_quest, name='quest_edit'),
        path('delete/', views.delete_quest, name='quest_delete'),
        path('publish/', views.publish_quest, name='quest_publish'),
        path('missions/', include([
            path('', views.quest_missions, name='quest_missions'),
            path('lines/', views.quest_lines, name='quest_lines'),
            path('lines/new/', views.create_line, name='line_new'),
            path('lines/<int:line_id>/', views.detail_line, name='line_detail'),
        ])),
        path('control/', include([
            path('', views.control_quest, name='quest_control'),
            path('begin/', views.begin_quest, name='begin_quest'),
            path('end/', views.end_quest, name='end_quest'),
            path('clear/', views.clear_quest, name='clear_quest'),
        ])),
        path('members/', include([
            path('', views.members_quest, name='quest_members'),
            path('players/', include([
                path('', views.players_quest, name='quest_players'),
                path('print/', views.players_quest_print, name='quest_players_print'),
                path('delete/', views.delete_players, name='players_delete'),
                path('delete/<int:user_id>/', views.delete_player, name='player_delete'),
            ])),
            path('organizers/', include([
                path('', views.organizers_quest, name='quest_organizers'),
                path('delete/<int:user_id>/', views.delete_organizer, name='organizer_delete'),
            ])),
        ])),
        path('coordination/', views.coordination_quest, name='quest_coordination'),
        path('coordination_ajax/', views.coordination_quest_ajax, name='quest_coordination_ajax'),
        path('tables/', include([
            path('', views.tables_quest, name='quest_tables'),
            path('current/', views.tables_quest_current, name='quest_tables_current'),
            path('all/', views.tables_quest_all, name='quest_tables_all'),
        ])),
        path('results/', views.results_quest, name='quest_results'),
        path('key_log/', include([
            path('', views.key_log_quest, name='quest_key_log'),
            path('delete/', views.delete_key_logs, name='key_logs_delete'),
            path('delete/<int:key_log_id>/', views.delete_key_log, name='key_log_delete'),
        ])),
        path('messages/', views.messages_quest, name='quest_messages'),
        path('messages/<int:message_id>/', include([
            path('show/', views.show_message, name='message_show'),
            path('edit/', views.edit_message, name='message_edit'),
            path('delete/', views.delete_message, name='message_delete'),
        ])),
    ])),
]

mission_patterns = [
    path('missions/new/<int:quest_id>/', views.create_mission, name='mission_new'),
    path('missions/<int:mission_id>/', include([
        path('', views.detail_mission, name='mission_detail'),
        path('edit/', views.edit_mission, name='mission_edit'),
        path('delete/', views.delete_mission, name='mission_delete'),
        path('picture/', views.picture_mission, name='mission_picture'),
    ])),
]

hint_patterns = [
    path('hints/<int:hint_id>/', include([
        path('edit/', views.edit_hint, name='hint_edit'),
        path('delete/', views.delete_hint, name='hint_delete'),
    ])),
]

urlpatterns = [
    re_path(r'^', include(quest_patterns)),
    re_path(r'^', include(mission_patterns)),
    re_path(r'^', include(hint_patterns)),
]

qc/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from main import views as main_views
from main.forms import AuthForm
from qc import settings
from qc.admin import admin_site

urlpatterns = [
    path('{}/'.format(settings.ADMIN_URL_PATH), admin_site.urls),
    path('login/', auth_views.LoginView.as_view(), {'authentication_form': AuthForm}, name='auth_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='auth_logout'),
    re_path(r'^$', main_views.home, name='home'),
    path('profile/', include([
        path('', main_views.my_profile, name='my_profile'),
        path('name_change/', main_views.change_name, name='name_change'),
        path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    ])),
    path('news/', include([
        path('', main_views.all_news, name='news'),
        path('<int:news_id>', main_views.detail_news, name='news_detail'),
    ])),
    path('help/', include([
        path('', main_views.help, name='help'),
        path('<int:category_id>/', main_views.help_category, name='help_category'),
    ])),
    re_path(r'^', include(('coordination.urls', 'coordination'), namespace='coordination')),
]

templates/coordination/quests/members/_nav.html
{% load main_extras %}
{% load coordination_extras %}

<ul class="nav nav-pills">
    {% if user|is_organizer:quest or user.is_superuser %}
       {% menu_item 'Игроки' 'coordination:quest_players' quest.id %}
       {% menu_item 'Организаторы' 'coordination:quest_organizers' quest.id %}
    {% endif %}
</ul>

templates/coordination/quests/members/organizers.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ quest.title }} - Организаторы{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>
    {% include 'coordination/quests/members/_nav.html' %}

    <div class="row row-margin">{% crispy form %}</div>

    <div class="row row-margin">
        <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
            <ul class="list-group">
                {% for org in organizers %}
                    <li class="list-group-item text-base clearfix{% if org == quest.creator %} active{% endif %}">
                        <span class="fa fa-user-secret fa-lg"></span> {{ org }}
                        {% if org != quest.creator and user != org %}
                        <button data-href="{% url 'coordination:organizer_delete' quest.id org.id %}" data-toggle="modal"
                                data-target="#confirm" class="btn btn-danger pull-right">
                            <span class="fa fa-trash fa-lg"></span> Удалить
                        </button>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

            {% if agent %}
                <h3>Агенты</h3>
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead>
                            <tr>
                                <th>Логин</th>
                                <th>Пароль</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ agent.username }}</td>
                                <td>{{ agent.last_name}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/coordination/quests/members/players.html
{% extends 'base_table.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ quest.title }} - Игроки{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>
    {% include 'coordination/quests/members/_nav.html' %}

    <div class="row row-margin">{% crispy form %}</div>

    <p class="text-center">
        <a href="{% url 'coordination:quest_players_print' quest.id %}" class="btn btn-primary" target="_blank">
            <span class="fa fa-print fa-lg"></span> Версия для печати
        </a>
    </p>

    <div id="toolbar">
        {% csrf_token %}
        <button id="remove" class="btn btn-danger" disabled data-toggle="modal" data-target="#confirm">
            <span class="fa fa-trash"></span> Удалить
        </button>
    </div>
    <table id="table" data-toggle="table" data-toolbar="#toolbar">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="id" class="hidden"></th>
                <th>Игрок</th>
                <th>Логин</th>
                <th>Пароль</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td></td>
                <td class="hidden">{{ player.id }}</td>
                <td>{{ player.first_name }}</td>
                <td>{{ player.username }}</td>
                <td>{{ player.last_name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var $table = $('#table');
        var $remove = $('#remove');
        var $confirm = $('#btn_confirm');

        $(function () {
            $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table', function () {
                $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
            });

            $confirm.click(function () {
                var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                    return row.id;
                });
                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: ids
                });
                $remove.prop('disabled', true);

                $.ajax({
                    "type": "POST",
                    "url": "{% url 'coordination:players_delete' quest.id %}",
                    "data": {'delete_ids': ids},
                    "success": function() {
                        window.location.reload(true);
                    }
                });
            });
        });
    </script>
{% endblock scripts %}

templates/coordination/quests/members/players_print.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/print.css" %}">
{% endblock %}

{% block title %}{{ quest.title }} - Игроки (печать){% endblock %}

{% block nav %}{% endblock %}

{% block content %}
    {% if players %}
        <table class="table text-center">
            <tbody>
            {% for player in players %}
                <tr>
                    <td>{{ player.first_name }}</td>
                    <td>Логин: <b>{{ player.username }}</b></td>
                    <td>Пароль: <b>{{ player.last_name }}</b></td>
                    <td>{{ request.get_host }}{% url 'auth_login' %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="lead text-center">Ни один игрок еще не добавлен к квесту.</p>
    {% endif %}
{% endblock content %}

{% block footer %}{% endblock %}

{% block scripts %}{% endblock %}