coordination/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from coordination.models import Quest
from . import views

quest_patterns = [
    path('quests/', views.all_quests, name='quests'),
    path('quests/new/', include([
        path('l/', views.create_quest, {'type': Quest.LINEAR}, name='quest_new_l'),
        path('nl/', views.create_quest, {'type': Quest.NONLINEAR}, name='quest_new_nl'),
        # TODO MC: 02.01.2019 uncomment when re-implement LNL quest
        # path('lnl/', views.create_quest, {'type': Quest.LINE_NONLINEAR}, name='quest_new_lnl'),
        path('ml/', views.create_quest, {'type': Quest.MULTILINEAR}, name='quest_new_ml'),
        path('type/', views.type_quest, name='quest_new_type'),
    ])),
    path('quests/<int:quest_id>/', include([
        path('', views.detail_quest, name='quest_detail'),
        path('edit/', views.edit_quest, name='quest_edit'),
        path('delete/', views.delete_quest, name='quest_delete'),
        path('publish/', views.publish_quest, name='quest_publish'),
        path('missions/', include([
            path('', views.quest_missions, name='quest_missions'),
            path('lines/', views.quest_lines, name='quest_lines'),
            path('lines/new/', views.create_line, name='line_new'),
            path('lines/<int:line_id>/', views.detail_line, name='line_detail'),
        ])),
        path('control/', include([
            path('', views.control_quest, name='quest_control'),
            path('begin/', views.begin_quest, name='begin_quest'),
            path('end/', views.end_quest, name='end_quest'),
            path('clear/', views.clear_quest, name='clear_quest'),
        ])),
        path('members/', include([
            path('', views.members_quest, name='quest_members'),
            path('players/', include([
                path('', views.players_quest, name='quest_players'),
                path('print/', views.players_quest_print, name='quest_players_print'),
                path('delete/', views.delete_players, name='players_delete'),
                path('delete/<int:user_id>/', views.delete_player, name='player_delete'),
            ])),
            path('organizers/', include([
                path('', views.organizers_quest, name='quest_organizers'),
                path('delete/<int:user_id>/', views.delete_organizer, name='organizer_delete'),
            ])),
        ])),
        path('coordination/', views.coordination_quest, name='quest_coordination'),
        path('coordination_ajax/', views.coordination_quest_ajax, name='quest_coordination_ajax'),
        path('tables/', include([
            path('', views.tables_quest, name='quest_tables'),
            path('current/', views.tables_quest_current, name='quest_tables_current'),
            path('all/', views.tables_quest_all, name='quest_tables_all'),
        ])),
        path('results/', views.results_quest, name='quest_results'),
        path('key_log/', include([
            path('', views.key_log_quest, name='quest_key_log'),
            path('delete/', views.delete_key_logs, name='key_logs_delete'),
            path('delete/<int:key_log_id>/', views.delete_key_log, name='key_log_delete'),
        ])),
        path('messages/', views.messages_quest, name='quest_messages'),
        path('messages/<int:message_id>/', include([
            path('show/', views.show_message, name='message_show'),
            path('edit/', views.edit_message, name='message_edit'),
            path('delete/', views.delete_message, name='message_delete'),
        ])),
    ])),
]

mission_patterns = [
    path('missions/new/<int:quest_id>/', views.create_mission, name='mission_new'),
    path('missions/<int:mission_id>/', include([
        path('', views.detail_mission, name='mission_detail'),
        path('edit/', views.edit_mission, name='mission_edit'),
        path('delete/', views.delete_mission, name='mission_delete'),
        path('picture/', views.picture_mission, name='mission_picture'),
    ])),
]

hint_patterns = [
    path('hints/<int:hint_id>/', include([
        path('edit/', views.edit_hint, name='hint_edit'),
        path('delete/', views.delete_hint, name='hint_delete'),
    ])),
]

urlpatterns = [
    re_path(r'^', include(quest_patterns)),
    re_path(r'^', include(mission_patterns)),
    re_path(r'^', include(hint_patterns)),
]

qc/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from main import views as main_views
from main.forms import AuthForm
from qc import settings
from qc.admin import admin_site

urlpatterns = [
    path('{}/'.format(settings.ADMIN_URL_PATH), admin_site.urls),
    path('login/', auth_views.LoginView.as_view(), {'authentication_form': AuthForm}, name='auth_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='auth_logout'),
    re_path(r'^$', main_views.home, name='home'),
    path('profile/', include([
        path('', main_views.my_profile, name='my_profile'),
        path('name_change/', main_views.change_name, name='name_change'),
        path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    ])),
    path('news/', include([
        path('', main_views.all_news, name='news'),
        path('<int:news_id>', main_views.detail_news, name='news_detail'),
    ])),
    path('help/', include([
        path('', main_views.help, name='help'),
        path('<int:category_id>/', main_views.help_category, name='help_category'),
    ])),
    re_path(r'^', include(('coordination.urls', 'coordination'), namespace='coordination')),
]

coordination/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from htmlmin.decorators import minified_response
from sendfile import sendfile

from coordination.forms import QuestForm, MissionForm, HintForm, PlayerForm, KeyForm, MessageForm, OrganizerForm
from coordination.models import Quest, Mission, Hint, KeyLog, Message, Membership, MissionLog
from coordination.permission_utils import is_quest_organizer, is_quest_player, is_organizer, is_quest_organizer_or_agent
from coordination.utils import generate_random_username, generate_random_password, get_timedelta, is_game_over, \
    is_ml_game_over, get_interval


# Quests
def all_quests(request):
    quest_list = Quest.objects.filter(parent__isnull=True).order_by('-start')
    paginator = Paginator(quest_list, 15)
    page = request.GET.get('page')
    try:
        quests = paginator.page(page)
    except PageNotAnInteger:
        quests = paginator.page(1)
    except EmptyPage:
        quests = paginator.page(paginator.num_pages)
    context = {'quests': quests}
    return render(request, 'coordination/quests/all.html', context)


def detail_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if not quest.published:
        request = is_quest_organizer(request, quest)
    interval = None
    if quest.nonlinear or quest.multilinear:
        interval = get_interval(quest.start, quest.game_over)
    context = {'quest': quest, 'interval': interval}
    return render(request, 'coordination/quests/detail.html', context)


@login_required()
def type_quest(request):
    request = is_organizer(request)
    return render(request, 'coordination/quests/type.html')


@login_required()
def create_quest(request, quest_type):
    request = is_organizer(request)
    if request.method == 'POST':
        form = QuestForm(request.POST)
        if form.is_valid():
            quest = form.save(commit=False)
            quest.creator = request.user
            quest.type = quest_type
            quest.save()
            return redirect('coordination:quest_detail', quest_id=quest.pk)
    else:
        form = QuestForm(type=quest_type, org_name=request.user.first_name)
    context = {'form': form}
    return render(request, 'coordination/quests/form.html', context)


@login_required()
def edit_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id)
    request = is_quest_organizer(request, quest)
    if request.method == "POST":
        form = QuestForm(request.POST, instance=quest)
        if form.is_valid():
            form.save()
            if quest.parent:
                return redirect('coordination:line_detail', quest_id=quest.parent.id, line_id=quest.id)
            else:
                return redirect('coordination:quest_detail', quest_id=quest.id)
    else:
        form = QuestForm(instance=quest)
    context = {'form': form}
    return render(request, 'coordination/quests/form.html', context)


@login_required
def delete_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id)
    is_quest_organizer(request, quest)
    quest.delete()
    if quest.parent:
        return redirect('coordination:quest_lines', quest_id=quest.parent.id)
    else:
        return redirect('coordination:quests')


@login_required
def publish_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.publish()
    return redirect('coordination:quest_detail', quest_id=quest_id)


@minified_response
def results_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if not quest.published:
        request = is_quest_organizer(request, quest)
    context = {'quest': quest, }
    if quest.nonlinear or quest.multilinear:
        players = quest.players_ext()
        missions = quest.missions_ext()
        context.update({'players': players, 'missions': missions})
    else:
        missions = quest.missions().exclude(is_finish=True)
        key_logs = KeyLog.right_key_logs(missions)
        current_missions = quest.current_missions()
        context.update({'missions': missions, 'key_logs': key_logs, 'current_missions': current_missions})
    return render(request, 'coordination/quests/results.html', context)


@login_required
def tables_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if quest.nonlinear or quest.multilinear:
        request = is_quest_organizer_or_agent(request, quest)
        players = quest.players_ext()
        missions = quest.missions_ext()
        context = {'quest': quest, 'players': players, 'missions': missions}
        if quest.nonlinear:
            return render(request, 'coordination/quests/tables/nonlinear.html', context)
        else:
            return render(request, 'coordination/quests/tables/multilinear.html', context)
    else:
        return redirect('coordination:quest_tables_current', quest_id=quest_id)


@login_required
@minified_response
def tables_quest_all(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, type__in=(Quest.LINEAR, Quest.LINE_NONLINEAR), parent__isnull=True)
    request = is_quest_organizer_or_agent(request, quest)
    players = quest.players()
    missions = quest.missions().exclude(is_finish=True)
    key_logs = KeyLog.right_key_logs(missions)
    context = {'quest': quest, 'players': players, 'missions': missions, 'key_logs': key_logs}
    return render(request, 'coordination/quests/tables/all.html', context)


@login_required
@minified_response
def tables_quest_current(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, type__in=(Quest.LINEAR, Quest.LINE_NONLINEAR), parent__isnull=True)
    request = is_quest_organizer_or_agent(request, quest)
    current_missions = quest.current_missions()
    context = {'quest': quest, 'current_missions': current_missions}
    return render(request, 'coordination/quests/tables/current.html', context)


@login_required
def control_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    context = {'quest': quest, }
    return render(request, 'coordination/quests/control.html', context)


@login_required
def begin_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.begin()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def end_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.end()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def clear_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    if quest.not_started:
        if quest.multilinear:
            lines = quest.lines()
            # TODO: additionally handle multiline quest
            MissionLog.objects.filter(mission__quest__in=lines).update(status=MissionLog.NOT_STARTED)
            KeyLog.objects.filter(mission__quest__in=lines).delete()
        else:
            MissionLog.objects.filter(mission__quest=quest).update(status=MissionLog.NOT_STARTED)
            MissionLog.objects.filter(mission=quest.start_mission).update(status=MissionLog.CURRENT)
            KeyLog.objects.filter(mission__quest=quest).delete()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def members_quest(request, quest_id):
    return redirect('coordination:quest_players', quest_id=quest_id)


@login_required
def players_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    players = quest.players()
    form = PlayerForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data["name"]
        username = generate_random_username(name)
        password = generate_random_password()
        user = User.objects.create_user(username=username, password=password, first_name=name, last_name=password)
        Membership.objects.create(quest=quest, user=user, role=Membership.PLAYER)
        # TODO: handle multiline quest
        if quest.linear or quest.line_nonlinear:
            for mission in quest.missions():
                MissionLog.objects.create(player=user, mission=mission, status=MissionLog.NOT_STARTED)
            MissionLog.objects.filter(player=user, mission=quest.start_mission).update(status=MissionLog.CURRENT)
        return redirect('coordination:quest_players', quest_id=quest_id)
    context = {'quest': quest, 'form': form, 'players': players}
    return render(request, 'coordination/quests/members/players.html', context)


@login_required
def players_quest_print(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    players = quest.players()
    context = {'quest': quest, 'players': players}
    return render(request, 'coordination/quests/members/players_print.html', context)


@login_required()
def organizers_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    organizers = quest.organizers()
    all_orgs = User.objects.filter(groups__name='organizers').exclude(id__in=organizers)
    if request.method == 'POST':

templates/coordination/missions/_lines_list.html
{% load coordination_extras %}

<div class="list-group">
    <a href="{% url 'coordination:mission_detail' mission_start.id %}" class="list-group-item text-base text-left">
        {{ mission_start }}
    </a>
    {% for line in lines %}
        <a href="{% url 'coordination:line_detail' quest.id line.id %}" class="list-group-item text-base text-left">
            {{ line }}
        </a>
    {% endfor %}
    <a href="{% url 'coordination:mission_detail' mission_finish.id %}" class="list-group-item text-base text-left">
        {{ mission_finish }}
    </a>
</div>

templates/coordination/missions/_list.html
{% load coordination_extras %}

<div class="list-group">
    {% for mission in missions %}
        <a href="{% url 'coordination:mission_detail' mission.id %}"
           class="list-group-item text-base text-left">
            {% if user|is_organizer:quest or user.is_superuser or user|is_agent:quest %}
                {{ mission }}
            {% else %}
                {{ mission.short_name }}
            {% endif %}
            {% if quest.nonlinear or line.parent %}
                {% if not mission.is_finish and not mission.is_start %}
                    <span class="text-medium badge"><span class="glyphicon glyphicon-piggy-bank"></span> {{ mission.points }}</span>
                {% endif %}
            {% endif %}
        </a>
    {% endfor %}
</div>

templates/coordination/missions/all.html
{% extends 'base.html' %}
{% load coordination_extras %}


{% block title %}{{ quest.title }} - Задания{% endblock %}

{% block content %}
    <div class="page-header">
            <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>

    {% if quest.not_started %}
        {% if user|is_organizer:quest or user.is_superuser %}
            <p class=" text-center">
                <a href="{% url 'coordination:mission_new' quest.id %}" class="btn btn-success">
                    <span class="fa fa-plus fa-lg"></span> Добавить задание
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if quest.ended or user|is_organizer:quest or user.is_superuser or user|is_agent:quest %}
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                {% include 'coordination/missions/_list.html' %}
            </div>
        </div>
    {% else %}
        <p class="lead text-center">Чтобы просмотреть задания, дождитесь окончания игры!</p>
        {% if user|is_player:quest %}
            <p class="lead text-center">Пройденные вами задания смотрите в разделе Координация.</p>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/coordination/missions/detail.html
{% extends 'base.html' %}
{% load coordination_extras %}
{% load crispy_forms_tags %}

{% block title %}{% if quest.parent %}{{ quest.parent.title }}.{% endif %} {{ quest.title }}. {{ mission.short_name }}{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{% if quest.parent %}{{ quest.parent.title }}.{% endif %} {{ quest.title }}.
            {% if user|is_organizer:quest or user.is_superuser or user|is_agent:quest %}
                {{ mission }}
            {% else %}
                {{ mission.short_name }}
            {% endif %}
        </h1>
    </div>

    {% if not quest.parent %}
        {% include 'coordination/quests/_nav.html' %}
        <br>
    {% else %}
        <p class="text-center">
            <a href="{% url 'coordination:line_detail' quest.parent_id quest.id %}" class="btn btn-default">
                Вернуться к заданиям линии</a>
        </p>
    {% endif %}

    {% if user|is_organizer:quest or user.is_superuser %}
        <p class="text-right">
            <a href="{% url 'coordination:mission_edit' mission.id %}" class="btn btn-primary">
                <span class="fa fa-edit fa-lg"></span> Редактировать
            </a>

            {% if not quest.started and not mission.is_start and not mission.is_finish %}
                <button data-href="{% url 'coordination:mission_delete' mission.id %}" data-toggle="modal"
                        data-target="#confirm" class="btn btn-danger">
                    <span class="fa fa-trash fa-lg"></span> Удалить
                </button>
            {% endif %}
        </p>
    {% endif %}

    <div class="text-base">{{ mission.text|safe }}</div>

    {% include 'coordination/quests/coordination/_picture.html' %}

    {% if quest.linear and not mission.is_finish or quest.nonlinear and not mission.is_finish and not mission.is_start %}
        <br>
        <p class="label label-info text-medium"><span class="fa fa-key"></span> {{ mission.key|default:"Не указан" }}</p>
    {% endif %}

    {% if quest.nonlinear or quest.parent %}
        {% if not mission.is_finish and not mission.is_start %}
            <p class="label label-default text-medium"><span class="glyphicon glyphicon-piggy-bank"></span> {{ mission.points }}</p>
        {% endif %}
    {% endif %}

    {% if user|is_organizer:quest or user.is_superuser%}
        {% if hint_form %}
            <h3>Подсказки</h3>
            <div id="hints" class="row">
                {% include 'coordination/hints/_list.html' %}
            </div>
            <h4>Добавить подсказку</h4>
            <form class="col-md-6 col-md-offset-3" action="" method="post">
                {% crispy hint_form %}
                <button type="submit" class="btn btn-success"><span class="fa fa-check"></span> Готово</button>
            </form>
        {% endif %}
    {% elif hints %}
        <h3>Подсказки</h3>
        <p class="text-center">Нажмите на заголовок подсказки, чтобы отобразить ее.</p>
        <div id="hints" class="row">
            {% include 'coordination/hints/_collapsing_list.html' %}
        </div>
    {% endif %}
{% endblock content %}

templates/coordination/missions/form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="page-header">
        <h1>{% block title %}{{ form.instance.pk|yesno:'Редактирование задания, Новое задание' }}{% endblock %}</h1>
    </div>

    <form class="col-md-6 col-md-offset-3" action="" method="post" enctype="multipart/form-data">
        {% crispy form %}
        <button type="submit" class="btn btn-success"><span class="fa fa-check"></span> Готово</button>

        <a href="
        {% if form.instance.pk %}
            {% url 'coordination:mission_detail' form.instance.pk %}
        {% else %}
            {% if quest.parent %}
                {% url 'coordination:line_detail' quest.parent.id quest.id %}
            {% else %}
                {% url 'coordination:quest_missions' quest.id %}
            {% endif %}
        {% endif %}
        " class="btn btn-default"><span class="fa fa-close"></span> Отмена</a>
    </form>
{% endblock content %}

templates/coordination/missions/line_detail.html
{% extends 'base.html' %}
{% load coordination_extras %}


{% block title %}{{ quest.title }} - {{ line.title }}. Задания{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
            <h1>{{ quest.title }}. {{ line.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>

    {% if user|is_organizer:quest or user.is_superuser %}
        <p class="text-right">
            <a href="{% url 'coordination:quest_edit' line.id %}" class="btn btn-primary">
                <span class="fa fa-edit fa-lg"></span> Редактировать
            </a>

            {% if not quest.started %}
                <button data-href="{% url 'coordination:quest_delete' line.id %}" data-toggle="modal"
                        data-target="#confirm" class="btn btn-danger">
                    <span class="fa fa-trash fa-lg"></span> Удалить
                </button>
            {% endif %}
        </p>
    {% endif %}

    {% if quest.not_started %}
        {% if user|is_organizer:quest or user.is_superuser %}
            <p class=" text-center">
                <a href="{% url 'coordination:mission_new' line.id %}" class="btn btn-success">
                    <span class="fa fa-plus fa-lg"></span> Добавить задание
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if quest.ended or user|is_organizer:quest or user.is_superuser or user|is_agent:quest %}
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                {% include 'coordination/missions/_list.html' %}
            </div>
        </div>
    {% else %}
        <p class="lead text-center">Чтобы просмотреть задания, дождитесь окончания игры!</p>
        {% if user|is_player:quest %}
            <p class="lead text-center">Пройденные вами задания смотрите в разделе Координация.</p>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/coordination/missions/lines.html
{% extends 'base.html' %}
{% load coordination_extras %}


{% block title %}{{ quest.title }} - Задания{% endblock %}

{% block content %}
    <div class="page-header">
            <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>

    {% if quest.not_started %}
        {% if user|is_organizer:quest or user.is_superuser %}
            <p class=" text-center">
                <a href="{% url 'coordination:line_new' quest.id %}" class="btn btn-success">
                    <span class="fa fa-plus fa-lg"></span> Добавить линию
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if quest.ended or user|is_organizer:quest or user.is_superuser or user|is_agent:quest %}
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                {% include 'coordination/missions/_lines_list.html' %}
            </div>
        </div>
    {% else %}
        <p class="lead text-center">Чтобы просмотреть задания, дождитесь окончания игры!</p>
        {% if user|is_player:quest %}
            <p class="lead text-center">Пройденные вами задания смотрите в разделе Координация.</p>
        {% endif %}
    {% endif %}
{% endblock content %}