coordination/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from coordination.models import Quest
from . import views

quest_patterns = [
    path('quests/', views.all_quests, name='quests'),
    path('quests/new/', include([
        path('l/', views.create_quest, {'type': Quest.LINEAR}, name='quest_new_l'),
        path('nl/', views.create_quest, {'type': Quest.NONLINEAR}, name='quest_new_nl'),
        # TODO MC: 02.01.2019 uncomment when re-implement LNL quest
        # path('lnl/', views.create_quest, {'type': Quest.LINE_NONLINEAR}, name='quest_new_lnl'),
        path('ml/', views.create_quest, {'type': Quest.MULTILINEAR}, name='quest_new_ml'),
        path('type/', views.type_quest, name='quest_new_type'),
    ])),
    path('quests/<int:quest_id>/', include([
        path('', views.detail_quest, name='quest_detail'),
        path('edit/', views.edit_quest, name='quest_edit'),
        path('delete/', views.delete_quest, name='quest_delete'),
        path('publish/', views.publish_quest, name='quest_publish'),
        path('missions/', include([
            path('', views.quest_missions, name='quest_missions'),
            path('lines/', views.quest_lines, name='quest_lines'),
            path('lines/new/', views.create_line, name='line_new'),
            path('lines/<int:line_id>/', views.detail_line, name='line_detail'),
        ])),
        path('control/', include([
            path('', views.control_quest, name='quest_control'),
            path('begin/', views.begin_quest, name='begin_quest'),
            path('end/', views.end_quest, name='end_quest'),
            path('clear/', views.clear_quest, name='clear_quest'),
        ])),
        path('members/', include([
            path('', views.members_quest, name='quest_members'),
            path('players/', include([
                path('', views.players_quest, name='quest_players'),
                path('print/', views.players_quest_print, name='quest_players_print'),
                path('delete/', views.delete_players, name='players_delete'),
                path('delete/<int:user_id>/', views.delete_player, name='player_delete'),
            ])),
            path('organizers/', include([
                path('', views.organizers_quest, name='quest_organizers'),
                path('delete/<int:user_id>/', views.delete_organizer, name='organizer_delete'),
            ])),
        ])),
        path('coordination/', views.coordination_quest, name='quest_coordination'),
        path('coordination_ajax/', views.coordination_quest_ajax, name='quest_coordination_ajax'),
        path('tables/', include([
            path('', views.tables_quest, name='quest_tables'),
            path('current/', views.tables_quest_current, name='quest_tables_current'),
            path('all/', views.tables_quest_all, name='quest_tables_all'),
        ])),
        path('results/', views.results_quest, name='quest_results'),
        path('key_log/', include([
            path('', views.key_log_quest, name='quest_key_log'),
            path('delete/', views.delete_key_logs, name='key_logs_delete'),
            path('delete/<int:key_log_id>/', views.delete_key_log, name='key_log_delete'),
        ])),
        path('messages/', views.messages_quest, name='quest_messages'),
        path('messages/<int:message_id>/', include([
            path('show/', views.show_message, name='message_show'),
            path('edit/', views.edit_message, name='message_edit'),
            path('delete/', views.delete_message, name='message_delete'),
        ])),
    ])),
]

mission_patterns = [
    path('missions/new/<int:quest_id>/', views.create_mission, name='mission_new'),
    path('missions/<int:mission_id>/', include([
        path('', views.detail_mission, name='mission_detail'),
        path('edit/', views.edit_mission, name='mission_edit'),
        path('delete/', views.delete_mission, name='mission_delete'),
        path('picture/', views.picture_mission, name='mission_picture'),
    ])),
]

hint_patterns = [
    path('hints/<int:hint_id>/', include([
        path('edit/', views.edit_hint, name='hint_edit'),
        path('delete/', views.delete_hint, name='hint_delete'),
    ])),
]

urlpatterns = [
    re_path(r'^', include(quest_patterns)),
    re_path(r'^', include(mission_patterns)),
    re_path(r'^', include(hint_patterns)),
]

qc/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from main import views as main_views
from main.forms import AuthForm
from qc import settings
from qc.admin import admin_site

urlpatterns = [
    path('{}/'.format(settings.ADMIN_URL_PATH), admin_site.urls),
    path('login/', auth_views.LoginView.as_view(), {'authentication_form': AuthForm}, name='auth_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='auth_logout'),
    re_path(r'^$', main_views.home, name='home'),
    path('profile/', include([
        path('', main_views.my_profile, name='my_profile'),
        path('name_change/', main_views.change_name, name='name_change'),
        path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    ])),
    path('news/', include([
        path('', main_views.all_news, name='news'),
        path('<int:news_id>', main_views.detail_news, name='news_detail'),
    ])),
    path('help/', include([
        path('', main_views.help, name='help'),
        path('<int:category_id>/', main_views.help_category, name='help_category'),
    ])),
    re_path(r'^', include(('coordination.urls', 'coordination'), namespace='coordination')),
]

coordination/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from htmlmin.decorators import minified_response
from sendfile import sendfile

from coordination.forms import QuestForm, MissionForm, HintForm, PlayerForm, KeyForm, MessageForm, OrganizerForm
from coordination.models import Quest, Mission, Hint, KeyLog, Message, Membership, MissionLog
from coordination.permission_utils import is_quest_organizer, is_quest_player, is_organizer, is_quest_organizer_or_agent
from coordination.utils import generate_random_username, generate_random_password, get_timedelta, is_game_over, \
    is_ml_game_over, get_interval


# Quests
def all_quests(request):
    quest_list = Quest.objects.filter(parent__isnull=True).order_by('-start')
    paginator = Paginator(quest_list, 15)
    page = request.GET.get('page')
    try:
        quests = paginator.page(page)
    except PageNotAnInteger:
        quests = paginator.page(1)
    except EmptyPage:
        quests = paginator.page(paginator.num_pages)
    context = {'quests': quests}
    return render(request, 'coordination/quests/all.html', context)


def detail_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if not quest.published:
        request = is_quest_organizer(request, quest)
    interval = None
    if quest.nonlinear or quest.multilinear:
        interval = get_interval(quest.start, quest.game_over)
    context = {'quest': quest, 'interval': interval}
    return render(request, 'coordination/quests/detail.html', context)


@login_required()
def type_quest(request):
    request = is_organizer(request)
    return render(request, 'coordination/quests/type.html')


@login_required()
def create_quest(request, quest_type):
    request = is_organizer(request)
    if request.method == 'POST':
        form = QuestForm(request.POST)
        if form.is_valid():
            quest = form.save(commit=False)
            quest.creator = request.user
            quest.type = quest_type
            quest.save()
            return redirect('coordination:quest_detail', quest_id=quest.pk)
    else:
        form = QuestForm(type=quest_type, org_name=request.user.first_name)
    context = {'form': form}
    return render(request, 'coordination/quests/form.html', context)


@login_required()
def edit_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id)
    request = is_quest_organizer(request, quest)
    if request.method == "POST":
        form = QuestForm(request.POST, instance=quest)
        if form.is_valid():
            form.save()
            if quest.parent:
                return redirect('coordination:line_detail', quest_id=quest.parent.id, line_id=quest.id)
            else:
                return redirect('coordination:quest_detail', quest_id=quest.id)
    else:
        form = QuestForm(instance=quest)
    context = {'form': form}
    return render(request, 'coordination/quests/form.html', context)


@login_required
def delete_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id)
    is_quest_organizer(request, quest)
    quest.delete()
    if quest.parent:
        return redirect('coordination:quest_lines', quest_id=quest.parent.id)
    else:
        return redirect('coordination:quests')


@login_required
def publish_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.publish()
    return redirect('coordination:quest_detail', quest_id=quest_id)


@minified_response
def results_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if not quest.published:
        request = is_quest_organizer(request, quest)
    context = {'quest': quest, }
    if quest.nonlinear or quest.multilinear:
        players = quest.players_ext()
        missions = quest.missions_ext()
        context.update({'players': players, 'missions': missions})
    else:
        missions = quest.missions().exclude(is_finish=True)
        key_logs = KeyLog.right_key_logs(missions)
        current_missions = quest.current_missions()
        context.update({'missions': missions, 'key_logs': key_logs, 'current_missions': current_missions})
    return render(request, 'coordination/quests/results.html', context)


@login_required
def tables_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    if quest.nonlinear or quest.multilinear:
        request = is_quest_organizer_or_agent(request, quest)
        players = quest.players_ext()
        missions = quest.missions_ext()
        context = {'quest': quest, 'players': players, 'missions': missions}
        if quest.nonlinear:
            return render(request, 'coordination/quests/tables/nonlinear.html', context)
        else:
            return render(request, 'coordination/quests/tables/multilinear.html', context)
    else:
        return redirect('coordination:quest_tables_current', quest_id=quest_id)


@login_required
@minified_response
def tables_quest_all(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, type__in=(Quest.LINEAR, Quest.LINE_NONLINEAR), parent__isnull=True)
    request = is_quest_organizer_or_agent(request, quest)
    players = quest.players()
    missions = quest.missions().exclude(is_finish=True)
    key_logs = KeyLog.right_key_logs(missions)
    context = {'quest': quest, 'players': players, 'missions': missions, 'key_logs': key_logs}
    return render(request, 'coordination/quests/tables/all.html', context)


@login_required
@minified_response
def tables_quest_current(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, type__in=(Quest.LINEAR, Quest.LINE_NONLINEAR), parent__isnull=True)
    request = is_quest_organizer_or_agent(request, quest)
    current_missions = quest.current_missions()
    context = {'quest': quest, 'current_missions': current_missions}
    return render(request, 'coordination/quests/tables/current.html', context)


@login_required
def control_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    context = {'quest': quest, }
    return render(request, 'coordination/quests/control.html', context)


@login_required
def begin_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.begin()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def end_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    quest.end()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def clear_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    is_quest_organizer(request, quest)
    if quest.not_started:
        if quest.multilinear:
            lines = quest.lines()
            # TODO: additionally handle multiline quest
            MissionLog.objects.filter(mission__quest__in=lines).update(status=MissionLog.NOT_STARTED)
            KeyLog.objects.filter(mission__quest__in=lines).delete()
        else:
            MissionLog.objects.filter(mission__quest=quest).update(status=MissionLog.NOT_STARTED)
            MissionLog.objects.filter(mission=quest.start_mission).update(status=MissionLog.CURRENT)
            KeyLog.objects.filter(mission__quest=quest).delete()
    return redirect('coordination:quest_control', quest_id=quest_id)


@login_required
def members_quest(request, quest_id):
    return redirect('coordination:quest_players', quest_id=quest_id)


@login_required
def players_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    players = quest.players()
    form = PlayerForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data["name"]
        username = generate_random_username(name)
        password = generate_random_password()
        user = User.objects.create_user(username=username, password=password, first_name=name, last_name=password)
        Membership.objects.create(quest=quest, user=user, role=Membership.PLAYER)
        # TODO: handle multiline quest
        if quest.linear or quest.line_nonlinear:
            for mission in quest.missions():
                MissionLog.objects.create(player=user, mission=mission, status=MissionLog.NOT_STARTED)
            MissionLog.objects.filter(player=user, mission=quest.start_mission).update(status=MissionLog.CURRENT)
        return redirect('coordination:quest_players', quest_id=quest_id)
    context = {'quest': quest, 'form': form, 'players': players}
    return render(request, 'coordination/quests/members/players.html', context)


@login_required
def players_quest_print(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    players = quest.players()
    context = {'quest': quest, 'players': players}
    return render(request, 'coordination/quests/members/players_print.html', context)


@login_required()
def organizers_quest(request, quest_id):
    quest = get_object_or_404(Quest, pk=quest_id, parent__isnull=True)
    request = is_quest_organizer(request, quest)
    organizers = quest.organizers()
    all_orgs = User.objects.filter(groups__name='organizers').exclude(id__in=organizers)
    if request.method == 'POST':

templates/coordination/quests/all.html
{% extends 'base.html' %}
{% load main_extras %}

{% block content %}
    <div class="page-header">
        <h1>{% block title %}Квесты{% endblock %}</h1>
    </div>

    <p class=" text-center">
        {% if user|in_group:'organizers' %}
            <a href="{% url 'coordination:quest_new_type' %}" class="btn btn-success">
                <span class="fa fa-plus fa-lg"></span> Создать квест
            </a>
        {% else %}
            <a href="{% url 'auth_login' %}?next={{request.path}}" class="btn btn-warning btn-responsive">
                <span class="fa fa-info"></span> Войдите в систему как организатор, чтобы создать квест!
            </a>
        {% endif %}
    </p>

    <div class="row">
        {% if quests %}
            <div class="col-md-10 col-md-offset-1">
                {% include 'coordination/quests/_list.html' %}
                {% include 'coordination/_pagination.html' with p=quests %}
            </div>
        {% else %}
            <p class="lead text-center">Пока нет ни одной игры.</p>
        {% endif %}
    </div>
{% endblock content %}

templates/coordination/quests/control.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ quest.title }} - Управление{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}

    {% if quest.not_started %}
        <p class="row-margin text-center">
            <button data-href="{% url 'coordination:clear_quest' quest.id %}" data-toggle="modal"
                    data-target="#confirm" class="btn btn-danger">
                <span class="fa fa-trash"></span> Очистить результаты квеста
            </button>
        </p>
    {% endif %}

    {% if quest.is_published %}
        {% if quest.not_started or quest.started %}
            <p class="row-margin text-center">
                {% url 'coordination:begin_quest' quest.id as begin_url %}
                {% if quest.not_started %}
                     <button data-href="{{ begin_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-success">
                         <span class="fa fa-play"></span> Начать квест
                     </button>
                {% elif quest.started %}
                    <button data-href="{{ begin_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-warning">
                        <span class="fa fa-pause"></span> Приостановить квест
                    </button>
                {% endif %}
            </p>
        {% endif %}

        {% if quest.started or quest.ended %}
            <p class="row-margin text-center">
                {% url 'coordination:end_quest' quest.id as end_url %}
                {% if quest.started %}
                     <button data-href="{{ end_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-danger">
                         <span class="fa fa-stop"></span> Завершить квест
                     </button>
                {% elif quest.ended %}
                    <button data-href="{{ end_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-warning">
                        <span class="fa fa-play"></span> Возобновить квест
                    </button>
                {% endif %}
            </p>
        {% endif %}
    {% else %}
        <p class="lead text-center">Опубликуйте квест для управления его состоянием.</p>
    {% endif %}
{% endblock content %}

templates/coordination/quests/coordination.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}{{ quest.title }} - Координация{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}

    <h2 id="mission_name">{{ mission.short_name }}</h2>

    <div class="row-margin text-base" id="countup"></div>

    <div id="messages">
        {% include 'coordination/messages/_list.html' %}
    </div>

    <div id="text" class="text-base">{{ mission.text|safe }}</div>

    <div id="picture">{% include 'coordination/quests/_picture.html' %}</div>

    <div class="text-base" id="countdown"></div>

    <div id="hints" class="row">
        {% include 'coordination/hints/_list.html' %}
    </div>

    <div id="form">
        {% if form %}
            <div class="row-margin">{% crispy form %}</div>
            <div id="wrong_keys">{% include 'coordination/quests/_wrong_keys.html' %}</div>
        {% endif %}
    </div>

    <div id="completed_missions" class="row-margin">
        {% include 'coordination/quests/_completed_missions.html' %}
    </div>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "assets/js/jquery.plugin.min.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/jquery.countdown.min.js" %}"></script>
    <script type="text/javascript">
        var url = "{% url 'coordination:quest_coordination_ajax' quest.id %}";
        $(function () {
            {% if delay %}
                start_countdown({{ delay }});
            {% endif %}

            {% now "U" as t %}
            var time = new Date({{ t }});
            start_countup(time)
        });

        setInterval(function () {
            update_coordination()
        }, 103000);
    </script>
    <script type="text/javascript" src="{% static "assets/js/coordination.js" %}"></script>
{% endblock %}

templates/coordination/quests/detail.html
{% extends 'base.html' %}
{% load coordination_extras %}


{% block title %}{{ quest.title }} - Об игре{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
            <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}
    <br>

    {% if user|is_organizer:quest or user.is_superuser %}
        <p class="text-right">
            <a href="{% url 'coordination:quest_edit' quest.id %}" class="btn btn-primary">
                <span class="fa fa-edit fa-lg"></span> Редактировать
            </a>

            {% if not quest.started %}
                <button data-href="{% url 'coordination:quest_delete' quest.id %}" data-toggle="modal"
                        data-target="#confirm" class="btn btn-danger">
                    <span class="fa fa-trash fa-lg"></span> Удалить
                </button>
            {% endif %}
        </p>

        <p class="text-right">
            {% url 'coordination:quest_publish' quest.id as publish_url %}
            {% if quest.is_published %}
                 <button data-href="{{ publish_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-warning">
                     <span class="fa fa-eye-slash fa-lg"></span> Снять квест с публикации
                 </button>
            {% else %}
                <button data-href="{{ publish_url }}" data-toggle="modal" data-target="#confirm" class="btn btn-success">
                    <span class="fa fa-eye fa-lg"></span> Опубликовать квест
                </button>
            {% endif %}
        </p>
    {% endif %}

    <h3>
        <span class="label {{ quest.ended|yesno:'label-default, label-info' }}">
            <span class="fa fa-clock-o fa-lg"></span>
            {{ quest.start|date:"d E Y в H:i"|default:"Скоро" }}
        </span>
    </h3>

    <h3 class="orgs">Организатор: <span class="label label-primary">{{ quest.organizer_name }}</span></h3>

    <h3>
        {% if quest.line_nonlinear %}<span class="fa fa-exchange"></span> Линейно-нелинейный квест{% endif %}
        {% if quest.nonlinear %}<span class="fa fa-arrows"></span> Нелинейный квест{% endif %}
        {% if quest.multilinear %}<span class="fa fa-tasks"></span> Многолинейный квест{% endif %}
    </h3>

    {% if interval %}<p><b>Продолжительность: {{ interval|format_interval }}</b></p>{% endif %}
    <div class="text-base">{{ quest.description|default:"Подробности позже."|safe }}</div>
{% endblock content %}

templates/coordination/quests/key_log.html
{% extends 'base_table.html' %}

{% block title %}{{ quest.title }} - История ключей{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}

    <br>

    <div class="row">
        <div class="col-sm-4 col-md-3">
        {% url 'coordination:quest_key_log' quest.id as key_log_url %}
            <h3>Задания</h3>
            <div class="list-group">
            {% if quest.multilinear %}
                {% regroup missions by quest as mission_list %}
                {% for quest in mission_list %}
                    <p class="list-group-item list-group-item-info">{{ quest.grouper }}</p>
                    {% for mission in quest.list %}
                        <a href="{{ key_log_url }}?mission={{ mission.id }}"
                           class="list-group-item{% if mission.id == cur_mission %} active{% endif %}">
                            {{ mission.medium_name }}
                        </a>
                    {% endfor %}
                {% endfor %}
            {% else %}
                {% for mission in missions %}
                    <a href="{{ key_log_url }}?mission={{ mission.id }}"
                       class="list-group-item{% if mission.id == cur_mission %} active{% endif %}">
                        {{ mission.medium_name }}
                    </a>
                {% endfor %}
            {% endif %}
            </div>

            {% if players %}
                <h3>Игроки</h3>
                <div class="list-group">
                    {% for player in players %}
                        <a href="{{ key_log_url }}?player={{ player.id }}"
                           class="list-group-item{% if player.id == cur_player %} active{% endif %}">
                            {{ player.first_name }}
                        </a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="col-sm-8 col-md-9">
            <div id="toolbar">
                {% csrf_token %}
                <button id="remove" class="btn btn-danger" disabled data-toggle="modal" data-target="#confirm">
                    <span class="fa fa-trash"></span> Удалить
                </button>
            </div>

            <table id="table" data-toggle="table" data-toolbar="#toolbar">
                <thead>
                    <tr>
                        <th data-field="state" data-checkbox="true"></th>
                        <th data-field="id" class="hidden"></th>
                        <th data-sortable="true">Игрок</th>
                        <th data-sortable="true">Задание</th>
                        <th data-sortable="true">Время ключа</th>
                        <th data-sortable="true">Ключ</th>
                    </tr>
                </thead>
                <tbody>
                {% for key_log in key_logs %}
                    <tr>
                        <td></td>
                        <td class="hidden">{{ key_log.id }}</td>
                        <td>{{ key_log.player.first_name }}</td>
                        <td><span class="hidden">{{ key_log.mission.order_number }}</span> {{ key_log.mission.medium_name }}</td>
                        <td>{{ key_log.fix_time|date:"d E Y H:i:s" }}</td>
                        <td>
                            <span class="fa {% if key_log.is_right %}fa-check-circle text-success{% else %}fa-minus-circle
                            text-danger{% endif %}"></span> {{ key_log.key }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var $table = $('#table');
        var $remove = $('#remove');
        var $confirm = $('#btn_confirm');

        $(function () {
            $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table', function () {
                $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
            });

            $confirm.click(function () {
                var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                    return row.id;
                });
                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: ids
                });
                $remove.prop('disabled', true);

                $.ajax({
                    "type": "POST",
                    "url": "{% url 'coordination:key_logs_delete' quest.id %}",
                    "data": {'delete_ids': ids},
                    "success": function() {
                        window.location.reload(true);
                    }
                });
            });
        });
    </script>
{% endblock scripts %}

templates/coordination/quests/players.html
{% extends 'base_table.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ quest.title }} - Игроки{% endblock %}

{% block content %}
    {% include 'coordination/_confirm_dialog.html' %}

    <div class="page-header">
        <h1>{{ quest.title }}</h1>
    </div>

    {% include 'coordination/quests/_nav.html' %}

    <div class="row row-margin">{% crispy form %}</div>

    <p class="text-center">
        <a href="{% url 'coordination:quest_players_print' quest.id %}" class="btn btn-primary" target="_blank">
            <span class="fa fa-print fa-lg"></span> Версия для печати
        </a>
    </p>

    <div id="toolbar">
        {% csrf_token %}
        <button id="remove" class="btn btn-danger" disabled data-toggle="modal" data-target="#confirm">
            <span class="fa fa-trash"></span> Удалить
        </button>
    </div>
    <table id="table" data-toggle="table" data-toolbar="#toolbar">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="id" class="hidden"></th>
                <th>Игрок</th>
                <th>Логин</th>
                <th>Пароль</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td></td>
                <td class="hidden">{{ player.id }}</td>
                <td>{{ player.first_name }}</td>
                <td>{{ player.username }}</td>
                <td>{{ player.last_name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script>
        var $table = $('#table');
        var $remove = $('#remove');
        var $confirm = $('#btn_confirm');

        $(function () {
            $table.on('check.bs.table uncheck.bs.table ' +
                    'check-all.bs.table uncheck-all.bs.table', function () {
                $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);
            });

            $confirm.click(function () {
                var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                    return row.id;
                });
                $table.bootstrapTable('remove', {
                    field: 'id',
                    values: ids
                });
                $remove.prop('disabled', true);

                $.ajax({
                    "type": "POST",
                    "url": "{% url 'coordination:players_delete' quest.id %}",
                    "data": {'delete_ids': ids},
                    "success": function() {
                        window.location.reload(true);
                    }
                });
            });
        });
    </script>
{% endblock scripts %}