coordination/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from coordination.models import Quest
from . import views

quest_patterns = [
    path('quests/', views.all_quests, name='quests'),
    path('quests/new/', include([
        path('l/', views.create_quest, {'type': Quest.LINEAR}, name='quest_new_l'),
        path('nl/', views.create_quest, {'type': Quest.NONLINEAR}, name='quest_new_nl'),
        # TODO MC: 02.01.2019 uncomment when re-implement LNL quest
        # path('lnl/', views.create_quest, {'type': Quest.LINE_NONLINEAR}, name='quest_new_lnl'),
        path('ml/', views.create_quest, {'type': Quest.MULTILINEAR}, name='quest_new_ml'),
        path('type/', views.type_quest, name='quest_new_type'),
    ])),
    path('quests/<int:quest_id>/', include([
        path('', views.detail_quest, name='quest_detail'),
        path('edit/', views.edit_quest, name='quest_edit'),
        path('delete/', views.delete_quest, name='quest_delete'),
        path('publish/', views.publish_quest, name='quest_publish'),
        path('missions/', include([
            path('', views.quest_missions, name='quest_missions'),
            path('lines/', views.quest_lines, name='quest_lines'),
            path('lines/new/', views.create_line, name='line_new'),
            path('lines/<int:line_id>/', views.detail_line, name='line_detail'),
        ])),
        path('control/', include([
            path('', views.control_quest, name='quest_control'),
            path('begin/', views.begin_quest, name='begin_quest'),
            path('end/', views.end_quest, name='end_quest'),
            path('clear/', views.clear_quest, name='clear_quest'),
        ])),
        path('members/', include([
            path('', views.members_quest, name='quest_members'),
            path('players/', include([
                path('', views.players_quest, name='quest_players'),
                path('print/', views.players_quest_print, name='quest_players_print'),
                path('delete/', views.delete_players, name='players_delete'),
                path('delete/<int:user_id>/', views.delete_player, name='player_delete'),
            ])),
            path('organizers/', include([
                path('', views.organizers_quest, name='quest_organizers'),
                path('delete/<int:user_id>/', views.delete_organizer, name='organizer_delete'),
            ])),
        ])),
        path('coordination/', views.coordination_quest, name='quest_coordination'),
        path('coordination_ajax/', views.coordination_quest_ajax, name='quest_coordination_ajax'),
        path('tables/', include([
            path('', views.tables_quest, name='quest_tables'),
            path('current/', views.tables_quest_current, name='quest_tables_current'),
            path('all/', views.tables_quest_all, name='quest_tables_all'),
        ])),
        path('results/', views.results_quest, name='quest_results'),
        path('key_log/', include([
            path('', views.key_log_quest, name='quest_key_log'),
            path('delete/', views.delete_key_logs, name='key_logs_delete'),
            path('delete/<int:key_log_id>/', views.delete_key_log, name='key_log_delete'),
        ])),
        path('messages/', views.messages_quest, name='quest_messages'),
        path('messages/<int:message_id>/', include([
            path('show/', views.show_message, name='message_show'),
            path('edit/', views.edit_message, name='message_edit'),
            path('delete/', views.delete_message, name='message_delete'),
        ])),
    ])),
]

mission_patterns = [
    path('missions/new/<int:quest_id>/', views.create_mission, name='mission_new'),
    path('missions/<int:mission_id>/', include([
        path('', views.detail_mission, name='mission_detail'),
        path('edit/', views.edit_mission, name='mission_edit'),
        path('delete/', views.delete_mission, name='mission_delete'),
        path('picture/', views.picture_mission, name='mission_picture'),
    ])),
]

hint_patterns = [
    path('hints/<int:hint_id>/', include([
        path('edit/', views.edit_hint, name='hint_edit'),
        path('delete/', views.delete_hint, name='hint_delete'),
    ])),
]

urlpatterns = [
    re_path(r'^', include(quest_patterns)),
    re_path(r'^', include(mission_patterns)),
    re_path(r'^', include(hint_patterns)),
]

qc/urls.py
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from main import views as main_views
from main.forms import AuthForm
from qc import settings
from qc.admin import admin_site

urlpatterns = [
    path('{}/'.format(settings.ADMIN_URL_PATH), admin_site.urls),
    path('login/', auth_views.LoginView.as_view(), {'authentication_form': AuthForm}, name='auth_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='auth_logout'),
    re_path(r'^$', main_views.home, name='home'),
    path('profile/', include([
        path('', main_views.my_profile, name='my_profile'),
        path('name_change/', main_views.change_name, name='name_change'),
        path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    ])),
    path('news/', include([
        path('', main_views.all_news, name='news'),
        path('<int:news_id>', main_views.detail_news, name='news_detail'),
    ])),
    path('help/', include([
        path('', main_views.help, name='help'),
        path('<int:category_id>/', main_views.help_category, name='help_category'),
    ])),
    re_path(r'^', include(('coordination.urls', 'coordination'), namespace='coordination')),
]

templates/_navbar.html
{% load static %}
{% load main_extras %}

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="inline-block" href="{% url 'home' %}">
                <img class="logo" src="{% static "assets/images/favicon-96x96.png" %}">
                <div class="brand">{{ PROJECT_NAME }}</div>
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% menu_item 'Квесты' 'coordination:quests' %}
                {% menu_item 'Новости' 'news' contains=True %}
                {% menu_item 'Помощь' 'help' contains=True %}
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}" target="_blank">Админка</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% url 'auth_login' as url_login %}
                {% if user.is_authenticated %}
                    {% if user|in_group:'organizers' %}
                        <li><a href="{% url 'my_profile' %}">
                            <span class="fa fa-user-secret fa-lg"></span> {{ user }}
                        </a></li>
                    {% elif user.is_superuser %}
                        <li class="navbar-text"><span class="fa fa-hand-spock-o fa-lg"></span> {{ user }}</li>
                    {% else %}
                       <li class="navbar-text"><span class="fa fa-user fa-lg"></span> {{ user }}</li>
                    {% endif %}
                    <li><p class="navbar-btn"><a href="{% url 'auth_logout' %}" class="btn btn-danger">
                        <span class="fa fa-sign-out fa-lg"></span> Выход</a></p></li>
                {% elif request.path != url_login %}
                    <li><p class="navbar-btn"><a href="{% url 'auth_login' %}?next={{ request.path }}" class="btn btn-default">
                        <span class="fa fa-sign-in fa-lg"></span> Вход</a></p></li>
                {% endif %}
            </ul>
        </div>
        <div class="text-base col-xs-12 col-sm-4 col-md-3" id="countup"></div>
        {% if quest and quest.nonlinear or quest.multilinear and quest.started and not quest.is_game_over %}
            <div class="text-base col-xs-12 col-sm-8 col-md-9" id="game_over_countdown"></div>
        {% endif %}
    </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    {% block metas %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="apple-touch-icon" sizes="57x57" href="{% static "assets/images/apple-touch-icon-57x57.png" %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static "assets/images/apple-touch-icon-60x60.png" %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static "assets/images/apple-touch-icon-72x72.png" %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/images/apple-touch-icon-76x76.png" %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static "assets/images/apple-touch-icon-114x114.png" %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static "assets/images/apple-touch-icon-120x120.png" %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static "assets/images/apple-touch-icon-144x144.png" %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static "assets/images/apple-touch-icon-152x152.png" %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/images/apple-touch-icon-180x180.png" %}">
        <meta name="apple-mobile-web-app-title" content="{{ PROJECT_NAME }}">

        <link rel="shortcut icon" href="{% static "assets/images/favicon.ico" %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static "assets/images/favicon-16x16.png" %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static "assets/images/favicon-32x32.png" %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/images/favicon-96x96.png" %}">
        <link rel="icon" type="image/png" sizes="160x160" href="{% static "assets/images/favicon-160x160.png" %}">
        <link rel="icon" type="image/png" sizes="192x192" href="{% static "assets/images/favicon-192x192.png" %}">

        <meta name="msapplication-TileColor" content="#2b5797">
        <meta name="msapplication-TileImage" content="{% static "assets/images/mstile-144x144.png" %}">
        <meta name="msapplication-config" content="{% static "assets/images/browserconfig.xml" %}">
        <meta name="application-name" content="{{ PROJECT_NAME }}">
    {% endblock metas %}

    <title>{% block title %}{% endblock %} | {{ PROJECT_NAME }}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "assets/css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" href="{% static "assets/css/font-awesome.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "assets/css/styles.css" %}">
    {% endblock styles %}

    {% block head-extra %}
        <script type="text/javascript" src="{% static "assets/js/jquery.min.js" %}"></script>
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% endblock head-extra %}
</head>

<body>
{% block nav %}{% include '_navbar.html' %}{% endblock %}

{% block jumbotron %}{% endblock %}

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}
    <div id="footer">
        <div class="container">
            <img class="logo" src="{% static "assets/images/favicon-96x96.png" %}">
            <div class="footer-text">
                {% now "Y" as current_year %}
                {{ FULL_PROJECT_NAME }} {{ PROJECT_VERSION }} <span class="fa fa-copyright"></span> {{ current_year }}
            </div>
            <a class="label label-info link" href="mailto:dev@quect.ru">
                <span class="fa fa-envelope"></span> dev@quect.ru</a>
            <a href="https://vk.com/true24quest" class="label label-info link">
                <span class="fa fa-vk fa-lg"></span> 24QUEST</a>
        </div>
    </div>
{% endblock footer %}

{% block scripts %}
    <script type="text/javascript" src="{% static "assets/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/main.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/jquery.plugin.min.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/jquery.countdown.min.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/coordination.js" %}"></script>
{% endblock scripts %}

<script type="text/javascript">
    $(function () {
        {% now "U" as t %}
        var time = new Date({{ t }});
        start_countup(time);

        {% if quest and quest.nonlinear or quest.multilinear %}
            start_game_over_countdown({{ quest.rest_quest }});
        {% endif %}
    });
</script>
</body>
</html>

templates/base_table.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "assets/css/bootstrap-table.min.css" %}">
{% endblock styles %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "assets/js/bootstrap-table.min.js" %}"></script>
    <script type="text/javascript" src="{% static "assets/js/bootstrap-table-ru-RU.min.js" %}"></script>
{% endblock scripts %}

templates/home.html
{% extends 'base.html' %}
{% load main_extras %}
{% load coordination_extras %}

{% block title %}Главная{% endblock %}

{% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>Привет, квестер!</h1>
            <p>Создай квест. Играй в квест. Координация в помощь.</p>
            {% if user|in_group:'organizers' %}
                <p><a class="btn btn-success btn-lg" href="{% url 'coordination:quest_new_type' %}">
                    <span class="fa fa-plus fa-lg"></span> Создать квест</a></p>
            {% elif quest and user|is_agent:quest %}
                <p><a class="btn btn-success btn-lg {% if not quest.is_published %}disabled{% endif %}"
                      href="{% url 'coordination:quest_detail' quest.id %}">
                    <span class="fa fa-user fa-lg"></span> К агентской игре</a></p>
            {% elif quest %}
                <p><a class="btn btn-success btn-lg {% if not quest.is_published %}disabled{% endif %}"
                      href="{% url 'coordination:quest_coordination' quest.id %}">
                    <span class="fa fa-user fa-lg"></span> Играть</a></p>
            {% elif user.is_superuser %}
                <p><a class="btn btn-success btn-lg" href="{% url 'admin:index' %}">
                    <span class="fa fa-hand-spock-o fa-lg"></span> Перейти в админку</a></p>
            {% else %}
                <p><a class="btn btn-success btn-lg" href="{% url 'auth_login' %}">
                        <span class="fa fa-sign-in fa-lg"></span> Вход</a></p>
            {% endif %}
            </div>
    </div>
{% endblock jumbotron %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h2><span class="fa fa-calendar-check-o"></span> Ближайшие игры</h2>
            {% if coming_quests %}
                {% include 'coordination/quests/_list.html' with quests=coming_quests %}
            {% else %}
                <p class="lead text-center">Отсутствуют.</p>
            {% endif %}
            <p><a class="btn btn-default" href="{% url 'coordination:quests' %}">
                Больше игр <span class="fa fa-angle-double-right"></span></a></p>
        </div>
        <div class="col-lg-6">
            <h2><span class="fa fa-newspaper-o"></span> Новости проекта</h2>
            {% if last_news %}
                {% include 'news/_list.html' with news_list=last_news %}
                <p><a class="btn btn-default" href="{% url 'news' %}">
                    Другие новости <span class="fa fa-angle-double-right"></span></a></p>
            {% else %}
                <p class="lead text-center">Отсутствуют.</p>
            {% endif %}
       </div>
    </div>
{% endblock content %}

templates/navbar.html
{% load staticfiles %}
{% load main_extras %}

<div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="inline-block" href="{% url 'home' %}">
                <img class="logo" src="{% static "assets/images/favicon-96x96.png" %}">
                <div class="brand">{{ PROJECT_NAME }}</div>
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% menu_item 'Квесты' 'coordination:quests' %}
                {% menu_item 'Контакты' %}
                {% menu_item 'Новости' %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% url 'auth_login' as url_login %}
                {% if user.is_authenticated %}
                    <li class="navbar-text">
                    {% if user|in_group:'organizers' %}
                        <span class="fa fa-user-secret fa-lg"></span>
                    {% elif user.is_superuser %}
                        <span class="fa fa-hand-spock-o fa-lg"></span>
                    {% else %}
                        <span class="fa fa-user fa-lg"></span>
                    {% endif %}
                    {{ user|nice_name }}</li>
                    <li><p class="navbar-btn"><a href="{% url 'auth_logout' %}" class="btn btn-danger">
                        <span class="fa fa-sign-out fa-lg"></span> Выход</a></p></li>
                {% elif request.path != url_login %}
                    <li><p class="navbar-btn"><a href="{% url 'auth_login' %}?next={{ request.path }}" class="btn btn-default">
                        <span class="fa fa-sign-in fa-lg"></span> Вход</a></p></li>
                {% endif %}
            </ul>
          </div>
        </div>
    </div>